languageCode: en-us
title: Hugo prototype

menus: main

ignoreFiles:
  - .gitignore
  - docker-compose.yml
  - Dockerfile
  - package.json
  - yarn.lock

module:
  mounts:
  - source: assets
    target: assets
  - source: node_modules
    target: assets
