version: "3.2"

services:
  hugo:
    build: ./
    volumes:
      - ./:/src
      - /src/node_modules
    ports:
      - "1313:1313"
    environment:
      HUGO_ENV: development
      HUGO_CACHEDIR: /src/resources/_cache
